### ISSUE TITLE
Problem on Synology NAS

### ISSUE THREAD

**Issue by jurekos** [milaq/YCast#102]
Hi trying to get working Ycast on Synology Nas but without success. Got installed python 3.8, pip, and others. When running it as root it seems ok:
`# python3 -m ycast -c /root/stations.yml -d
2021-10-19 12:13:07 INFO: YCast (1.1.0) server starting
2021-10-19 12:13:07 DEBUG: Debug logging enabled
 * Serving Flask app 'ycast.server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2021-10-19 12:13:07 WARNING:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-19 12:13:07 INFO:  * Running on http://192.168.8.107:80/ (Press CTRL+C to quit)`
but when trying access from browser: 192.168.8.107:80 got "Internal Server Error"
and this errors:
`
2021-10-19 12:17:27 ERROR: Exception on /ycast/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.8/site-packages/ycast/server.py", line 151, in landing
    len(my_stations.get_category_directories())))
  File "/usr/lib/python3.8/site-packages/ycast/my_stations.py", line 64, in get_category_directories
    categories.append(generic.Directory(category, len(get_stations_by_category(category))))
  File "/usr/lib/python3.8/site-packages/ycast/my_stations.py", line 73, in get_stations_by_category
    station_url = my_stations_yaml[category][station_name]
TypeError: string indices must be integers
2021-10-19 12:17:27 INFO: 10.8.0.6 - - [19/Oct/2021 12:17:27] "GET /ycast/ HTTP/1.1" 500 -`
is any hope to me to running this stuff? Dont know Python so good.
Have Yamaha RX-V453.
-- 
jureko

**Comment by TheBossME** [comment]
Have you tried dockerized ?. What model do you have ?.

**Comment by jurekos** [comment]
> Have you tried dockerized ?. What model do you have ?.

DS118. Dont have docker installed, It's a bit complicated on this model.
But have running coreelec with docker (on odroid), maybe this is good idea...
