### ISSUE TITLE
Denon AVR-X2200W produces unhandled queries

### ISSUE THREAD

**Issue by tomtastic** [milaq/YCast#47]
Denon AVR-X2200W working well, but I see these errors in the log after a power-on:
```
2020-04-19 15:47:54 ERROR: Unhandled upstream query (/setupapp/denon/asp/func/dynamOD.asp)
2020-04-19 15:48:27 ERROR: Unhandled upstream query (/setupapp/denon/asp/func/dynamOD.asp)
```

And if I follow the Denon webUI interface link for 'Jump to vTuner' :
```
2020-04-19 16:01:54 ERROR: Unhandled upstream query (/setupapp/denon/asp/AuthLogin/SignIn.asp)
```

**Comment by milaq** [comment]
Thanks for reporting :1st_place_medal: 
See https://github.com/milaq/YCast/commit/d0c87277a96526aadd1b639d22244d214f9215de

> `2020-04-19 16:01:54 ERROR: Unhandled upstream query (/setupapp/denon/asp/AuthLogin/SignIn.asp)`

Uff, this seems like a new one. I'll keep this issue open for further investigation later.

**Comment by D0m3L** [comment]
@milaq for the information - the same case for DENON AVR-X1200W - streaming working fine but some ERROR can be seen in logs:

> ERROR: Unhandled upstream query (/setupapp/denon/asp/func/dynamOD.asp)

Thanks for your work.

**Comment by ulrich-mayer** [comment]
@milaq  also have an DENON AVR-X1200W and see the unhandled query.
In addition I see this exception a couple of times:
```
2020-11-28 14:33:43 ERROR: Exception on /setupapp/denon/asp/browsexm2/loginXML.asp [GET]
Traceback (most recent call last):
  File "/home/umayer/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/umayer/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/umayer/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/umayer/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/umayer/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/umayer/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/umayer/.local/lib/python3.6/site-packages/ycast/server.py", line 135, in upstream
    return landing()
  File "/home/umayer/.local/lib/python3.6/site-packages/ycast/server.py", line 151, in landing
    len(my_stations.get_category_directories())))
  File "/home/umayer/.local/lib/python3.6/site-packages/ycast/my_stations.py", line 64, in get_category_directories
    categories.append(generic.Directory(category, len(get_stations_by_category(category))))
  File "/home/umayer/.local/lib/python3.6/site-packages/ycast/my_stations.py", line 72, in get_stations_by_category
    for station_name in my_stations_yaml[category]:
TypeError: 'NoneType' object is not iterable
```
I've pip3'ed it today (2020-11-28) and ran it locally (`python -m ycast`)

I don't think it matters, but nevertheless: 
My `stations.yml` is rather simple (my first experiment...):
```
pop:
SWR1: http://swr-swr1-bw.cast.addradio.de/swr/swr1/bw/mp3/128/stream.mp3
SWR3: http://swr-swr3-live.cast.addradio.de/swr/swr3/live/mp3/128/stream.mp3

klassik:
SWR2: http://swr-swr2-live.cast.addradio.de/swr/swr2/live/mp3/256/stream.mp3
```
Please let me know how I can help to further nail this down.
Thank you!

### Nevermind, I fixed the indentation in my `stations.yml` and removed empty lines.
With this `stations.yml` it works perfectly well:
```
pop:
  SWR1: http://swr-swr1-bw.cast.addradio.de/swr/swr1/bw/mp3/128/stream.mp3
  SWR3: http://swr-swr3-live.cast.addradio.de/swr/swr3/live/mp3/128/stream.mp3
klassik:
  SWR2: http://swr-swr2-live.cast.addradio.de/swr/swr2/live/mp3/256/stream.mp3
```

This is the console output now:
```
 * Serving Flask app "ycast.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2020-11-28 16:46:21 WARNING: No icon information found for station with id 'MY_9B081852506D'
2020-11-28 16:46:33 WARNING: No icon information found for station with id 'MY_8120D675124F'
```
@tomtastic, @D0m3L, maybe your issues are also related to the yml file?

@milaq thank you for providing ycast :) You can put the AVR-X1200W on the list of supported devices.
The only caveat is: favorites from vtuner.com don't work anymore, maybe you want to mention that in readme.md
```
2020-11-28 16:46:21 WARNING: No icon information found for station with id 'MY_9B081852506D'
2020-11-28 16:46:33 WARNING: No icon information found for station with id 'MY_8120D675124F'
2020-11-28 16:56:55 ERROR: Unhandled upstream query (/setupapp/denon/asp/func/dynamOD.asp)
2020-11-28 16:57:04 ERROR: Unhandled upstream query (/setupapp/denon/asp/func/dynamOD.asp)
```

**Comment by tomtastic** [comment]
I'm using a fork with a few manual changes currently so I can't say for sure, but I'm almost 100% my stations.yml was formatted correctly as I have vim-syntactic loaded up with yamllint for these very reasons :)

**Comment by TheBossME** [comment]
Ulrich, please take the Stations Example to Test.
Bea

**Comment by ulrich-mayer** [comment]
@TheBossME I agree, that would have been the right approach. Now that it works I don't see a reason to do that exercise.

**Comment by TheBossME** [comment]
Blanks at Beginng in the subsection.., you‘ve created with Text Editor, Right ?

**Comment by ulrich-mayer** [comment]
Yes, I did. Maybe a message indicating invalid yml would be a good idea?

> Blanks at Beginng in the subsection.., you‘ve created with Text Editor, Right ?

**Comment by TheBossME** [comment]
SWR Radio:
  SWR1 Baden Württemberg: http://mp3-live.swr.de/swr1bw_m.m3u
  SWR1 Rheinland Pfalz: http://mp3-live.swr.de/swr1rp_m.m3u
  SWR1 RADIObox: http://swr-swr-raka01.cast.addradio.de/swr/swr/raka01/mp3/128/stream.mp3
  SWR2: http://mp3-live.swr.de/swr2_m.m3u
  SWR3: http://mp3-live.swr3.de/swr3_m.m3u
  SWR3 Specials: http://swr-swr-raka08.cast.addradio.de/swr/swr/raka08/mp3/128/stream.mp3
  SWR4: http://mp3-live.swr.de/swr4bw_m.m3u
  SWR4 Tübingen: http://mp3-live.swr.de/swr4tu_m.m3u
  Das Ding: http://mp3-live.dasding.de/dasding_m.m3u
  SWR Aktuell: http://mp3-live.swr.de/swraktuell_m.m3u

**Comment by TheBossME** [comment]
Add 2 Blanks add the beginning Lines of each station.

This is my List.

**Comment by tomtastic** [comment]
I recommend using https://codebeautify.org/yaml-validator/ if you want to verify your `stations.yml` is correctly formatted.

**Comment by tomtastic** [comment]
To get back to the original issue (in my view unrelated to all the mis-formatted `station.yml` files)....

Clicking the 'Jump to vTuner' link on the webUI of the AVR tries to visit :
`http://denon.vtuner.com/setupapp/denon/asp/AuthLogin/SignIn.asp`

For which ycast returns a 404 :
```
2020-11-29 10:17:52 ERROR: Unhandled upstream query (/setupapp/denon/asp/AuthLogin/SignIn.asp)
2020-11-29 10:17:52 INFO: 172.27.0.12 - - [29/Nov/2020 10:17:52] "GET /setupapp/denon/asp/AuthLogin/SignIn.asp HTTP/1.1" 404 -
```
