### ISSUE TITLE
Access errors

### ISSUE THREAD

**Issue by maks2018** [milaq/YCast#5]
Thanks for your work! But, often I get the message "access error" on the screen when I start the RX-773

**Comment by milaq** [comment]
Weird,
access errors are thrown by the vtuner client if the server didn't send a correctly formatted access token.

We send the AVRs a bogus token and it seems to work uniformly.
See https://github.com/milaq/YCast/blob/master/ycast.py#L40

What do you mean with "often"? Does this happen intermittently?

**Comment by maks2018** [comment]
There is no regularity. In ~30% of cases, when turned on, I get an error.

**Comment by maks2018** [comment]
error:
```
GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?token=0 
GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?token=0
```
no error:
```
GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?token=0 
GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=0000000001000000E42B&fver=W&dlang=rus&startitems=1&enditems=10
```

**Comment by milaq** [comment]
That's weird.
The AVR requests the expected URI (`loginXML.asp?token=0`).

I tried to reproduce it myself with my AVRs but didn't run into the issue you are describing.
Maybe the YCast server answers too late.

If you have the time and are willing to, could you send me a `tcpdump` package dump of the traffic between your AVR and the host running YCast?
Even more awesome would be, as long as vTuner is still up, sniffing the traffic between your AVR and the official vTuner API.
Let me know if you require assistance.

Thanks and cheers

**Comment by Zippo2000** [comment]
I don't know if this is the same problem:
I have a RX-V3900. I can access the categories arranged in the stations.yml, but entering one of the folders ends in "no content" (kein Inhalt). I also tried your dev branch with the same result.

"GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=dcf51c28dcfcaebe40e061352c92902b&dlang=ger&fver=W&start=1&howmany=8 HTTP/1.1" 200 

Thank You

**Comment by Zenith-Nadir** [comment]
@Zippo2000:
Have you tried examples file, to see if it will work: https://github.com/milaq/YCast/blob/master/examples/stations.yml.example.
I was getting errors in the past, due to stations.yml file content formatting.
Also, ycast custom stations file is very sensitive to character set used, it accepts ASCII, but does not like UTF-8 (foreign/extended) characters, though in such case I was getting "Access Error".
First thing is just to try examples file, renaming to stations.yml to see if it works with your equipment.
Good Luck
Z-N

**Comment by Zippo2000** [comment]
@Zenith-Nadir :
Thank you for this hint. Using the standard stations.yml was the first thing I tried after recognizing something is going wrong. Sadly I got the same result.

But:
Today I do not get the error mentioned above. Now I get the same error @maks2018 mentioned in his post:

`"GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?token=0 HTTP/1.1" 200 -`
"Access Error" (Zugriffehler), and I can't access the top folders (categories) any more.
It is curious, I did not change anything. 

How can I investigate further more?

**Comment by Zippo2000** [comment]
OK, one step further.
Maybe the "new" situation is related to DNS. 

At first I only created a DNS entry for radioyamaha.vtuner.com
This led to the error `"GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=dcf51c28dcfcaebe40e061352c92902b&dlang=ger&fver=W&start=1&howmany=8 HTTP/1.1" 200`. This way I can access the categories defined in stations.yml, but without content.

Then I deleted the DNS entry and created a new one for vtuner.com with wildcard for all subdomains
Then I get the error `"GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?token=0 HTTP/1.1" 200 -` with "Access Error" when trying to open the categories 

What am I doing wrong?

By the way: Entering the address `http://radioyamaha.vtuner.com/ycast/Casual` in chrome:
`Station76Radiohttp://192.240.102.133:9566/streamStationAllzic Radio R&Bhttp://allzic10.ice.infomaniak.ch/allzic10.mp3StationJazz Radio Electro Swinghttp://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3StationSomaFM Beat Blenderhttp://ice1.somafm.com/beatblender-128-mp3StationSomaFM Groove Saladhttp://ice1.somafm.com/groovesalad-256-mp3StationSomaFM Lushhttp://ice1.somafm.com/lush-128-mp3StationThe UK 1940s Radio Stationhttp://91.121.134.23:8100/1`

**Comment by Zenith-Nadir** [comment]
Hello,
Do not use ampersand character "&", ycast does NOT like it and causes Access Error as in R&B. Also colon ":" character within stations names is NOT allowed.
I do not know what router settings you got, 
I use dd-wrt and I entered in dnsmasq: address=/radioyamaha.vtuner.com/radioyamaha2.vtuner.com/192.168.xxx.yyy.
Only, plain: radioyamaha.vtuner.com and radioyamaha2.vtuner.com.
The address 192.168.xxx.yyy points to my Ubuntu machine hosting ycast.
As it is a server, it should use static, and not DHCP address. I use standard ycast port of 8010.
I do not use wildcard in vtuner DNS, since I still want to access internet vtuner site. Just only those two as indicated above.

Feel free to ask more questions, if I can answer, I will.
Good Luck.
UPDATE: Actually "&" symbol is permitted, however colon ":" seems like is not (inside Stations names), as well as extended characters (non ASCII), like umlauts, accented characters, etc., might cause problems and "Access Error".
Z-N

**Comment by milaq** [comment]
I noticed that in the request from the Yamaha RX-V3900 @Zippo2000 uses there is a new parameters I have not seen before (`start=1&howmany=8`). At the moment we filter the result count by `startitems` and `enditems`. Some AVRs don't like the whole list pushed to them.
I'll add a separate filter for `start` and `howmany`.

Regarding the prohibited symbols @Zenith-Nadir mentioned: Maybe we should add a check for such characters. I'll try to reproduce the issue.

Also, it seems like some AVRs require a different format for the "access token".
@Zippo2000 can you remove the DNS redirects and sniff the traffic (e.g. with `tcpdump` or `Wireshark`) to the regular vTuner API after depowering the AVR completely (deplug from wall socket)? Specifically the access token request answer after `/setupapp/Yamaha/asp/BrowseXML/loginXML.asp?token=0`.
That'd be awesome. Maybe we can identify the correct format for your AVR.
You can also contact me via Email or direct message if you need assistance (native German tongue here).

**Comment by milaq** [comment]
I changed the way the element count is calculated (see https://github.com/milaq/YCast/commit/4fb591a18b39d0f4074f854b3a78922748670b8c) and added support for the new request params (see https://github.com/milaq/YCast/commit/f42b86cd401d6d67f1c1655e83fdd06b9ec131df).

Please let me know how it works for you now.

P.S.: Please use the [dev branch](https://github.com/milaq/YCast/tree/dev) for testing.

**Comment by Zippo2000** [comment]
> @Zippo2000 can you remove the DNS redirects and sniff the traffic (e.g. with `tcpdump` or `Wireshark`) to the regular vTuner API after depowering the AVR completely (deplug from wall socket)? Specifically the access token request answer after `/setupapp/Yamaha/asp/BrowseXML/loginXML.asp?token=0`.

Thank you for your reply!
I just installed wireshark to sniff the traffic - but I wasn't very successful, never did that before. Can you give some instructions how to set the correct filter?
I did not find any traffic from my receiver to radioyamaha.vtuner.com, just presumably UPNP-Traffic to my notebook. 
Sorry for OT

**Comment by milaq** [comment]
Hey Zippo,

@AlfredJ91 pointed out in https://github.com/milaq/YCast/issues/7 that the format of the access token response was incorrect. We _hopefully_ fixed that issue with https://github.com/milaq/YCast/commit/63b87dfa9586c46ae0744d9d3cb07e55c1fdcf7d.

As for sniffing traffic: First off, thanks for your endeavours :+1: 
You need to make sure that you _see_ all the packets from your AVR to the public internet. It all depends on your network infrastructure, but assuming a simple "Home router" (a.k.a. "Plasterouter" in german) layout where all your devices are _not_ connected to the same "collision domain" (read 'switch port'/'router port') and without any port mirroring, you need to have a way to either tunnel the traffic from your AVR through your capture device (in your case, your notebook) or capture the packets directly on your router. Else you will just see broadcast traffic such as UPNP as you noticed correctly.

Please don't tear down your whole infrastructure just to capture some packets for us ;)
Maybe we can fix your issues without any packet captures.
Though, if you are interested in packet capturing in general, I can can talk you through the process via voice if you like.

Can you try the lastest dev branch? I made some changes that may help.

Cheers

**Comment by Zippo2000** [comment]
Hello together,
thank you for your help!
I just installed the latest dev branch - but sadly all I get to see at console still is:
`"GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?token=0 HTTP/1.1" 200 -`
`"GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&dlang=ger&fver=W&start=1&howmany=8 HTTP/1.1" 200 -`
On TV/receiver menu I can access the "Radiobrowser" and "My Stations" (if stations.yml supplied), but again entering one of the items results in "no content" / "Kein Inhalt".

One more question regarding sniffing: So if I understood right I should activate port mirroring at my central switch, connect my notebook to that port and try again with wireshark?

What else can I do to analyze the problem?

**Comment by AlfredJ91** [comment]
Hello Zippo,

For that issue, I've Added in vtuner.py:
        etree.SubElement(item, 'DirCount').text = '2'
just before
        etree.SubElement(item, 'UrlDirBackUp').text = add_bogus_parameter(self.destination)

And my "Stations.yml" contains 2 stations.
Doing that I no longer get [NO CONTENT] and I see my station names. However when I select one of them I get "Access error'.
Milaq would like some captures of a real exchange to vtuner to go further but I don't know how to send it in private.

Regards,

Alfred

**Comment by milaq** [comment]
@Zippo2000 
Yes, you may connect to a port that mirrors the port your AVR is attached to. In promiscuous mode, you should then be able to capture any traffic for/to the AVR.
Alternatively you can run tcpdump directly on your router.

Apart from packet capturing, any tests you do with the dev branch help narrowing down the problem.
It seems like there are different versions of the vTuner API used on AVRs. So testing and posting the results (with logs) is very helpful.

@AlfredJ91 
Please see my comment here: https://github.com/milaq/YCast/issues/7#issuecomment-521614818

**Comment by Zippo2000** [comment]
Hi milaq,
I still didn't manage to get some traffic capture. But I tested the newest dev-branch and now I can see all stations in "My Stations" and "Radiobrowser". Selecting one station still ends in "access error".

Now I get the following messages:
`2019-08-18 12:48:39 INFO: 192.168.177.71 - - [18/Aug/2019 12:48:39] "GET /setupapp/Yamaha/asp/BrowseXML/statxml.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&fver=W&id=MY_000000 HTTP/1.1" 200 -
2019-08-18 12:48:39 INFO: 192.168.177.71 - - [18/Aug/2019 12:48:39] "GET /ycast/radiobrowser/?vtuner=true HTTP/1.1" 200 -
`

**Comment by milaq** [comment]
Hello @Zippo2000,

thanks for your response. Based on your log, I tried to guess what the correct vTuner API response would be and added the ability to fetch a single station here https://github.com/milaq/YCast/commit/b447eccd028b39ab350800ed674356ba85573f26.
Please get the latest [fetch_single_station](https://github.com/milaq/YCast/tree/fetch_single_station) branch (the linked commit is _not_ included in the dev branch for now) and see if it works.

Note: I also changed the way logging works. Please make sure you run YCast with the newly added `-d` parameter to get a verbose log.

Thanks and cheers

**Comment by Zippo2000** [comment]
Hello milaq,
thank you for your instant reply. Using the fetch_single_station branch now I receive the following messages when selecting a station within my **stations.yml** (followed by an "**access error**" on receiver display):
`2019-08-19 19:24:28 ERROR: Exception on /setupapp/Yamaha/asp/BrowseXML/statxml.asp [GET]
Traceback (most recent call last):
  File "/home/XXX/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/XXX/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/XXX/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/XXX/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/XXX/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/XXX/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/XXX/YCast_single/ycast/server.py", line 100, in landing
    station = get_station_by_id(request.args.get('id'))
  File "/home/XXX/YCast_single/ycast/server.py", line 87, in get_station_by_id
    return my_stations.get_station_by_id(generic.get_stationid_without_prefix(stationid)).to_vtuner()
AttributeError: 'NoneType' object has no attribute 'to_vtuner'
2019-08-19 19:24:29 INFO: 192.168.177.71 - - [19/Aug/2019 19:24:29] "GET /setupapp/Yamaha/asp/BrowseXML/statxml.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&fver=W&id=MY_000000 HTTP/1.1" 500 -
`


Selecting a station within **Radiobrowser**:
`2019-08-19 19:40:11 DEBUG: Radiobrowser API request: stations/byid/117825
2019-08-19 19:40:11 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-19 19:40:11 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/stations/byid/117825 HTTP/1.1" 200 837
2019-08-19 19:40:11 INFO: 192.168.177.71 - - [19/Aug/2019 19:40:11] "GET /setupapp/Yamaha/asp/BrowseXML/statxml.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&fver=W&id=RB_117825 HTTP/1.1" 200 -
`
There now I do not get an "access error" but "**buffering**"...but nothing more happens.

Again: Thank you for the great work!

**Comment by milaq** [comment]
Hi,

I should have mentioned that single station fetching is currently only supported for Radiobrowser stations as we don't have proper UID generation for custom stations. Sorry about that.

Nevertheless, the server shouldn't throw an exception. I fixed that with https://github.com/milaq/YCast/commit/4f6be40da9de02cd8f12d3798200fd0f25e0ead1

But that we now get "Buffering" means that we are doing _something_ right :1st_place_medal: 

Can you try the latest [fetch_single_station](https://github.com/milaq/YCast/tree/fetch_single_station) branch with other Radiobrowser stations? That way, we can make sure it is not an incompatible codec or the likes and not the listing itself.
I know for certain that "Mongoradio" works properly for most AVRs. When you browse the 'Most Popular' section, you should find it right at the top.

Thanks for your feedback and good night

**Comment by Zippo2000** [comment]
Hi milaq,

thank you!
"Mangoradio" was the first station I tried yesterday :-)
I tried again with the latest fetch_single_station branch but without success.
`2019-08-20 14:28:54 DEBUG: Radiobrowser API request: stations/byid/118926
2019-08-20 14:28:54 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-20 14:28:54 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/stations/byid/118926 HTTP/1.1" 200 723
2019-08-20 14:28:54 INFO: 192.168.177.71 - - [20/Aug/2019 14:28:54] "GET /setupapp/Yamaha/asp/BrowseXML/statxml.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&fver=W&id=RB_118926 HTTP/1.1" 200 -
`

Same result with each of the other stations.

**Comment by milaq** [comment]
Maybe the single station element requires a whole page surrounding the element.
Can you try the latest single_station_branch which includes https://github.com/milaq/YCast/commit/195c6fdc5beed2f09fc1f8c257a68a3247258438

Thanks for your help, you're awesome.

Cheers

**Comment by Zippo2000** [comment]
Hi milaq,

I just tried to play "MANGORADIO" (and other stations) with the latest single_station_branch -> **"access error"**

The complete log:
`2019-08-21 15:20:52 INFO: 192.168.177.71 - - [21/Aug/2019 15:20:52] "GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&dlang=eng&fver=W&start=1&howmany=8 HTTP/1.1" 200 -
2019-08-21 15:20:52 INFO: 192.168.177.71 - - [21/Aug/2019 15:20:52] "GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&dlang=ger&fver=W&start=1&howmany=8 HTTP/1.1" 200 -
2019-08-21 15:20:54 DEBUG: Radiobrowser API request: tags?hidebroken=true
2019-08-21 15:20:54 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:20:54 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/tags?hidebroken=true HTTP/1.1" 200 None
2019-08-21 15:20:54 DEBUG: Radiobrowser API request: countries?hidebroken=true
2019-08-21 15:20:54 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:20:54 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/countries?hidebroken=true HTTP/1.1" 200 None
2019-08-21 15:20:54 DEBUG: Radiobrowser API request: stations?order=votes&reverse=true&limit=200
2019-08-21 15:20:54 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:20:54 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/stations?order=votes&reverse=true&limit=200 HTTP/1.1" 200 None
2019-08-21 15:20:54 INFO: 192.168.177.71 - - [21/Aug/2019 15:20:54] "GET /ycast/radiobrowser/?vtuner=true&mac=65956752e8db8b1bf7fbd136ef719ea8&dlang=ger&fver=W&start=1&howmany=8 HTTP/1.1" 200 -
2019-08-21 15:20:54 DEBUG: Radiobrowser API request: tags?hidebroken=true
2019-08-21 15:20:54 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:20:54 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/tags?hidebroken=true HTTP/1.1" 200 None
2019-08-21 15:20:55 DEBUG: Radiobrowser API request: countries?hidebroken=true
2019-08-21 15:20:55 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:20:55 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/countries?hidebroken=true HTTP/1.1" 200 None
2019-08-21 15:20:55 DEBUG: Radiobrowser API request: stations?order=votes&reverse=true&limit=200
2019-08-21 15:20:55 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:20:55 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/stations?order=votes&reverse=true&limit=200 HTTP/1.1" 200 None
2019-08-21 15:20:55 INFO: 192.168.177.71 - - [21/Aug/2019 15:20:55] "GET /ycast/radiobrowser/?vtuner=true&mac=65956752e8db8b1bf7fbd136ef719ea8&dlang=ger&fver=W&start=1&howmany=8 HTTP/1.1" 200 -
2019-08-21 15:20:58 DEBUG: Radiobrowser API request: stations?order=votes&reverse=true&limit=200
2019-08-21 15:20:58 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:20:58 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/stations?order=votes&reverse=true&limit=200 HTTP/1.1" 200 None
2019-08-21 15:20:58 INFO: 192.168.177.71 - - [21/Aug/2019 15:20:58] "GET /ycast/radiobrowser/popular/?vtuner=true&mac=65956752e8db8b1bf7fbd136ef719ea8&dlang=ger&fver=W&start=1&howmany=8 HTTP/1.1" 200 -
2019-08-21 15:21:00 DEBUG: Radiobrowser API request: stations/byid/118926
2019-08-21 15:21:00 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:21:00 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/stations/byid/118926 HTTP/1.1" 200 723
2019-08-21 15:21:00 INFO: 192.168.177.71 - - [21/Aug/2019 15:21:00] "GET /setupapp/Yamaha/asp/BrowseXML/statxml.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&fver=W&id=RB_118926 HTTP/1.1" 200 -
`

Thanks.

STOP: **The station "SomaFM GROOVE Salad" is working!!!**
`2019-08-21 15:25:00 DEBUG: Radiobrowser API request: stations?order=votes&reverse=true&limit=200
2019-08-21 15:25:00 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:25:00 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/stations?order=votes&reverse=true&limit=200 HTTP/1.1" 200 None
2019-08-21 15:25:00 INFO: 192.168.177.71 - - [21/Aug/2019 15:25:00] "GET /ycast/radiobrowser/popular/?vtuner=true&mac=65956752e8db8b1bf7fbd136ef719ea8&dlang=ger&fver=W&start=1&howmany=8 HTTP/1.1" 200 -
2019-08-21 15:25:07 DEBUG: Radiobrowser API request: stations/byid/41976
2019-08-21 15:25:07 DEBUG: Starting new HTTP connection (1): www.radio-browser.info
2019-08-21 15:25:07 DEBUG: http://www.radio-browser.info:80 "GET /webservice/json/stations/byid/41976 HTTP/1.1" 200 768
2019-08-21 15:25:07 INFO: 192.168.177.71 - - [21/Aug/2019 15:25:07] "GET /setupapp/Yamaha/asp/BrowseXML/statxml.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&fver=W&id=RB_41976 HTTP/1.1" 200 -
`
The station **is not** working with the **"regular" dev branch**.

**Comment by milaq** [comment]
Hi Zippo,

thanks for reporting back. Good news! We're getting there somehow.
Please see my message here: https://github.com/milaq/YCast/issues/7#issuecomment-523911963
Can you test this?

Based on your comment that Mongoradio didn't work and SomaFM did, another thing came to my mind. What if the AVR can't display PNGs (the stationlogos) or has a problem with the dimensions.
That's the next thing we can try.

On a second thought: Both logos are served via https. This should work either way. But maybe still worth a try.
Maybe it is also the two redirects which the mongoradio url does. The SomaFM url is a direct binary stream.

**Comment by Zippo2000** [comment]
Hello milaq,

I just tried some more radio stations in popular folder: Besides SomaFM the stations BR-Klassik and 2ROCK are also working.  Perhaps it helps to investigate further.

Maybe a silly question: Where should the stationslogos be shown? I think my receiver simply can't do that. Even with original vTuner-service I have never seen logos...

Regarding [#7 (comment)](https://github.com/milaq/YCast/issues/7#issuecomment-523911963)
"My Stations" is working. Whatever custom station I select, it seems to play always the first station entry. 
`2019-08-22 19:37:04 INFO: 192.168.177.71 - - [22/Aug/2019 19:37:04] "GET /setupapp/Yamaha/asp/BrowseXML/statxml.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&fver=W&id=MY_000000 HTTP/1.1" 200 -
`

**Comment by milaq** [comment]
Thanks for your tests :+1: 

I added the "single station" functionality to the dev branch (see https://github.com/milaq/YCast/commit/19e0ff8649c36b0b9cd57c339e2339833aad3902) which now also includes some fixes and enhancements.
Specifically the ability to get custom stations by id, which should fix the issue with custom stations always returning the first element.

I'll have a look at the non-working stations and try to find out what makes the AVR to refuse them.

The stationlogos are usually shown in the companion app or on your TV screen. The RX-V3900 is an older model; maybe it doesn't have that functionality.

**Comment by Zippo2000** [comment]
Hello milaq,

since the integration of "single station" into dev branch I cannot start YCast any more:
`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/XXX/YCast_dev/ycast/__main__.py", line 8, in <module>
    from ycast import server
  File "/home/XXX/YCast_dev/ycast/server.py", line 9, in <module>
    import ycast.station_icons as station_icons
  File "/home/XXX/YCast_dev/ycast/station_icons.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'`

Do you know what the problem is?

**Comment by milaq** [comment]
Hi Zippo,

you are missing the newly added `Pillow` module for station icon conversion.
You can fix this by either installing your distribution's Python package (e.g. `python-pil` for Debian) or install `Pillow` via `pip`.

Once we resolve most of the issues (we're almost there), I'll distribute an updated version of the ycast package to PiPy for easy and hassle free installation.

**Comment by Zippo2000** [comment]
Hi milaq,
you're completly right, I totally missed that. Sorry.

But: With the dev branch again I get "access error". I even do not get into listing page with "radiobrowser" and "my stations". 
`2019-08-26 19:50:17 INFO: 192.168.177.71 - - [26/Aug/2019 19:50:17] "GET /setupapp/Yamaha/asp/BrowseXML/statxml.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&fver=W&id=MY_000000 HTTP/1.1" 200 -
2019-08-26 19:50:21 INFO: 192.168.177.71 - - [26/Aug/2019 19:50:21] "GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=65956752e8db8b1bf7fbd136ef719ea8&dlang=eng&fver=W&start=1&howmany=8 HTTP/1.1" 302 -`

**Comment by milaq** [comment]
> you're completly right, I totally missed that. Sorry.

No need to apologize. You're welcome :)

There seems to be an issue with some AVRs that can't handle 302 redirects properly.
I am investigating the issue and already stripped the redirecting from the landing page (see https://github.com/milaq/YCast/commit/987951e43f92ae96f458409a1219da08a2c73013).

Still, we need the redirects for station tracking and playlist support. If we can't get around having the affected receivers work properly with redirects we might need to find another solution.
But for now I am trying to pinpoint the issue (which is kind of hard, because all my AVRs work fine with the redirects).
I'll keep you posted and might ask for a test run or two :+1: 

Cheers

**Comment by milaq** [comment]
Please see my comment here https://github.com/milaq/YCast/issues/7#issuecomment-525407356 regarding the redirect issues.

**Comment by milaq** [comment]
Merging with https://github.com/milaq/YCast/issues/19.
Please report any additional issues there.
